In [6]:
import numpy as np
gameA = np.random.randint(-10, 10, (5, 5))
gameB = -gameA
print(gameA)
print(gameB)

[[-5 -4  5 -2 -8]
 [-1 -3  5  4 -9]
 [ 9 -8  6  4  6]
 [ 8  8 -7 -3 -2]
 [ 0  8  5  6  3]]
[[ 5  4 -5  2  8]
 [ 1  3 -5 -4  9]
 [-9  8 -6 -4 -6]
 [-8 -8  7  3  2]
 [ 0 -8 -5 -6 -3]]


In [9]:
 # Find dominant strategies for Player 1
dominant_strategies_p1 = np.where(gameA.max(axis=1) == gameA.min(axis=1))[0]
print(dominant_strategies_p1)
# Find dominant strategies for Player 2
dominant_strategies_p2 = np.where(gameB.max(axis=0) == gameB.min(axis=0))[0]
# Find the intersection of dominant strategies for both players
equilibrium_strategies = np.intersect1d(dominant_strategies_p1, dominant_strategies_p2)


(array([], dtype=int64),)
